## Day 5 HW

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。

In [5]:
import numpy as np

a = np.arange(11)
a[3:7] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

In [18]:
A = np.random.rand(3, 6)
ans = len(A[A>0.5])
print(A)
print(ans)

[[0.53027735 0.07209794 0.58353086 0.79125599 0.70234812 0.43463638]
 [0.23494824 0.95638957 0.42499188 0.04485215 0.45896109 0.67812368]
 [0.23591836 0.63196575 0.5026153  0.95928866 0.89555688 0.18212521]]
10
