## Day 6 HW

### 1. [簡答題] 請問下列這三種方法有什麼不同？

In [1]:
import numpy as np 

a = np.arange(6)

print(a.sum()) 
print(np.sum(a)) 
print(sum(a))

15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。

In [27]:
# Normalize: z = (x-mean)/std
A = np.random.random((5, 5))

# determine the mean and standard deviation of A
mean = np.mean(A)
std = np.std(A)

# normalization
norm_A = (A-mean)/std
print('Original Array: ', '\n', A)
print('Normalized Array: ', '\n', norm_A)

Original Array:  
 [[0.56234149 0.00558553 0.80916692 0.74335664 0.8857026 ]
 [0.97748436 0.07575679 0.69191102 0.97082555 0.75318673]
 [0.50625488 0.00169955 0.15323255 0.51632632 0.70748137]
 [0.31282661 0.95423378 0.65061108 0.88886614 0.25283221]
 [0.51262481 0.98335873 0.23120507 0.60972521 0.04308382]]
Normalized Array:  
 [[ 0.03192342 -1.68461569  0.79291306  0.59001282  1.02888088]
 [ 1.31185401 -1.4682701   0.43140037  1.29132419  0.62032005]
 [-0.14099769 -1.69659661 -1.22940389 -0.10994636  0.47940546]
 [-0.73735806  1.24016996  0.30406818  1.03863443 -0.92232731]
 [-0.12135849  1.32996532 -0.98900616  0.17801258 -1.5690044 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。

In [44]:
a = np.random.randint(1, 100, size=10)
print('Original Array: ', a)
max_num = a.max()
a[a == max_num] = -1
print('Modified Array: ', a)

Original Array:  [89  5 39 67 22 98 50  8  6 29]
Modified Array:  [89  5 39 67 22 -1 50  8  6 29]
