# Day 3 HW

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [11]:
zero_array = np.zeros((2,3))
empty_array = np.empty((2,3))
print('zeros() ==> ', zero_array)
print('empty() ==> ', empty_array)

# Answer:
# zeros(): 可以依照傳入的形狀引數，建立元素全為 0的array
# empty(): 不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定

zeros() ==>  [[0. 0. 0.]
 [0. 0. 0.]]
empty() ==>  [[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [57]:
a = np.random.rand(2, 3)*100

# use round method to turn floats to integers
int_array = np.round(a)

print('original array: ', a)
print('\n')
print('integer_array: ', int_array)

original array:  [[57.76556982 11.85113026 64.23576165]
 [14.33422298 65.9681077  92.72714966]]


integer_array:  [[58. 12. 64.]
 [14. 66. 93.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [52]:
m = 20
n = 40

a = np.random.rand(2, 3)
a = (a * (n - m) + m).round()

print(a)

[[37. 32. 32.]
 [26. 22. 27.]]
